LinkListQueue: LinkListQueue.c
	gcc -g -Wall -o LinkListQueue LinkListQueue.c
LinkListStack: LinkListStack.c
	gcc -g -Wall -o LinkListStack LinkListStack.c
DynArrayStack: DynArrayStack.c
	gcc -g -Wall -o DynArrayStack DynArrayStack.c
LinkListDeque: LinkListDeque.c
	gcc -g -Wall -o LinkListDeque LinkListDeque.c
DynArrayDeque: DynArrayDeque.c
	gcc -g -Wall -o DynArrayDeque DynArrayDeque.c
DynArrayBag: DynArrayBag.c
	gcc -g -Wall -o DynArrayBag DynArrayBag.c
DynamicArray: DynamicArray.c
	gcc -g -Wall -o DynamicArray DynamicArray.c
LinkListBag: LinkListBag.c
	gcc -g -Wall -o LinkListBag LinkListBag.c
BitSet: BitSet.c
	gcc -g -Wall -o BitSet BitSet.c
Sort: Sort.c
	gcc -g -Wall -o Sort Sort.c

clean:
	$(RM) LinkListQueue LinkListStack DynArrayStack LinkListDeque DynArrayDeque DynArrayBag DynamicArray LinkListBag BitSet Sort
